services:
  backend:
    build: .
    container_name: todo_app_backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: todo_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:                 # ← ровно на том же уровне, что backend / db
    build:
      context: ../my-frontend-project
    working_dir: /my-frontend-project
    volumes:
      - ../my-frontend-project:/my-frontend-project
    ports:
      - "5173:5173"
    command: npm run dev -- --host

volumes:
  postgres_data: